### ISSUE TITLE
CULTY DATA-Observations on CultyData

### ISSUE THREAD

**Issue by Farhath-Ayesha** [CULTYDATA/cultydata.github.io#37]
1. When clicking on the testimonials section on the home page, it fails to update and display new content.

![Image](https://github.com/user-attachments/assets/8c494288-3512-485a-99b8-517fd4d7a201)

2. A hyperlink should be provided for the privacy policy.

![Image](https://github.com/user-attachments/assets/0e302f33-2b83-4f16-b692-6100d805c9bd)

3.  The gap between sections is too large.

![Image](https://github.com/user-attachments/assets/0afc6a12-1eac-4f56-b41e-d9bcec5e2979)

4. The color format of the text is inconsistent

![Image](https://github.com/user-attachments/assets/1f263ecb-dac0-4961-9f10-ed2e781e60de)
5.Type issue

![Image](https://github.com/user-attachments/assets/8ff74c44-3388-44f8-afb2-fb5e77c73b28)
6.When the language is changed from English to French (FR), the 'View Details' text is not updated

![Image](https://github.com/user-attachments/assets/b932aa13-8733-42b4-af7e-05f2405e0077)

7. There is no need for dots as we have only one example

![Image](https://github.com/user-attachments/assets/09f1fda8-331c-41d1-a8fe-217470e10bf6)

8. Mismatch between English and French translations for some sentences.
   For example : 
English:  Access to talent pools from Cultydata Academy, creating internal synergies and fostering continuous innovation.
french:   Accès aux viviers de talents de Cultydata Academy, créant des synergies internes et favorisant l'innovation continue.

But it displays
French: Accès à des viviers de talents de la Cultydata Academy, créant des synergies internes et favorisant l'innovation continue.
English: Access to Cultydata Academy talent pools, creating internal synergies and promoting continuous innovation.

**Comment by vijayakumari2** [comment]
The first observation is resolved, but two marks are displaying. Apart from that, all remaining observations are resolved.



![Image](https://github.com/user-attachments/assets/6f848ede-6a60-4938-9a05-f037ff1c3858)

**Comment by Farhath-Ayesha** [comment]
@vijayakumari2 can you please retest now. It has been fixed.

**Comment by vijayakumari2** [comment]
Thanks @Farhath-Ayesha All  Observations  are fixed
